=== DRunING/ToMaTo/docs/formats/tutorial_list.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string",
        "format": "uri",
        "description": "URL of the tutorial description file, relative to this file"
      },
      "name": {
        "type": "string",
        "description": "A short name for the tutorial"
      },
      "desc": {
        "type": "string",
        "description": "A small text describing the contents of the tutorial and the target audience"
      },
      "icon": {
        "type": "string",
        "format": "uri",
        "description": "A 32x32 icon for this tutorial, url is relative to this file"
      }
    },
    "required": ["url", "name"]
  }
}

=== DRunING/ToMaTo/contrib/tutorials/index.json
[
  {
    "url":   "chat/tutorial.json",
    "name": "Chat Tutorial",
    "desc": "Get an overview over ToMaTo and its major features in a scenario using a text-based chat client.",
    "icon": "chat/icon.png"
  },
  {
    "url":   "basic/tutorial.json",
    "name": "Beginner Tutorial",
    "desc": "Teaches the basics about how to use ToMaTo's editor.",
    "icon": "basic/icon.png"
  },
  {
    "url":   "data_access/tutorial.json",
    "name": "Data Access",
    "desc": "Teaches various methods on how to upload and/or download data to/from the devices",
    "icon": "data_access/icon.png"
  },
  {
    "url":   "connections/tutorial.json",
    "name": "Using Connections",
    "desc": "Learn everything about connections. (currently under construction)",
    "icon": "connections/icon.png"
  } 
]
